server:
  port: 8086
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis_pluss?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mybatis:
  configuration:
    auto-mapping-behavior: full
    use-column-label: true
  mapper-locations: classpath:com/wxp/question/mapper/*.xml
  type-aliases-package: com.wxp.question.pojo
#显示SQL语句
logging:
  level:
    com:
      wxp:
        question:
          Mapper: debug



